#!/usr/bin/env python3

import os
import subprocess

from src.data import list_inputs

FRAMERATE = 0.10
OUTPUT_DIR = "data/image-seq"

for id, cls, description in list_inputs:
    output_subdir = os.path.join(OUTPUT_DIR, id)

    if os.path.exists(output_subdir):
        print(id, description, 'has been skipped as frames already exist!')
        continue

    os.makedirs(output_subdir)

    input_path = os.path.join(input_dir, filename)
    output_path = os.path.join(output_subdir, "output_%04d.png")

    cmd = f'ffmpeg -i "{input_path}" -r {FRAMERATE} "{output_path}"'
    subprocess.run(cmd, shell=True)
