#!/usr/bin/env python3

from ultralytics import YOLO

kwargs = {}
if 'KCL' in os.environ and os.environ['KCL'] == '1':
    # saturate RTX A5000 GPU
    kwargs['batch'] = 128

model = YOLO('yolov8n-seg.pt')
results = model.train(data='data/dataset.yaml', epochs=150, imgsz=640, **kwargs)